Added SPARQL* support for update queries
rubensworks/fetch-sparql-endpoint.js pull request #68
Opened 2023-09-03 03:44 UTC by albaike

Added option `sparqlStar` for to the `SparqlEndpointFetcher` constructor which enables support for SPARQL* when calling `getUpdateTypes`

2023-09-04 06:37 UTC, rubensworks requested changes
Thanks for the contribution @albaike!

I don't think we need the `sparqlStar` flag here in our constructor though. It's fine to just always enable `sparqlStar` support in the SPARQL parser. (this will soon become default everywhere in RDF 1.2, so we might as well support this fully from now on, as there are no breaking changes for existing queries)

2023-09-04 06:37 UTC, rubensworks commented on lib/SparqlEndpointFetcher.ts
> +    this.sparqlStar = args.sparqlStar || true;
As written this way, this will always be `true`, due to the `|| true`.

2023-09-05 06:42 UTC, merged

2023-09-05 06:43 UTC, rubensworks commented
Great; released as 4.1.0!

2023-09-05 22:06 UTC, albaike commented
I found another bug relating to SPARQL*:

`getQueryType` does not have SPARQL* support enabled so it throws an error instead of returning `'UNKNOWN'` on update queries.

For example this line throws the error so is unable to parse a star update: [https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts#L98](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts#L98)

2023-09-06 05:33 UTC, rubensworks commented
I already ammended your contribution with this change here, which should be present in the latest release: https://github.com/rubensworks/fetch-sparql-endpoint.js/commit/facef06abf09d377655b9ea3c090c65036c1c7e4